### ISSUE TITLE
Please add support to have existing PVC

### ISSUE THREAD

**Issue by govindkailas** [aquasecurity/harbor-scanner-trivy#79]
Currently in value.yaml what I see is the below,
```
persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 5Gi
```

Is there a way to add the existing pvc? I tried the below, but it doesn't seem to be working.
```
persistence:
  enabled: false
  resourcePolicy: "keep"
  persistentVolumeClaim:
    existingClaim: "trivy-claim"
    storageClass: ""
    accessMode: ReadWriteOnce
    size: 2Gi
```
